/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#151c27",
        "on-primary-fixed": "#002111",
        "inverse-primary": "#75daa1",
        "primary-fixed-dim": "#75daa1",
        "on-surface-variant": "#3e4941",
        surface: "#f9f9ff",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#dce2f3",
        "inverse-surface": "#2a313d",
        "tertiary-container": "#676e81",
        "on-background": "#151c27",
        error: "#ba1a1a",
        tertiary: "#4f5667",
        "surface-variant": "#dce2f3",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#006d42",
        "on-error": "#ffffff",
        "tertiary-fixed": "#dce2f7",
        "error-container": "#ffdad6",
        "secondary-container": "#d8e5e0",
        "on-secondary-fixed-variant": "#3d4946",
        "tertiary-fixed-dim": "#c0c6db",
        background: "#f9f9ff",
        "on-secondary-container": "#5b6763",
        "on-primary-container": "#caffdb",
        "on-tertiary-fixed-variant": "#404758",
        "on-tertiary-container": "#eff2ff",
        primary: "#00633c",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#bcc9c5",
        "inverse-on-surface": "#ebf1ff",
        "on-secondary-fixed": "#121e1b",
        "secondary-fixed": "#d8e5e0",
        "on-primary-fixed-variant": "#005231",
        "primary-fixed": "#92f7bb",
        "surface-dim": "#d3daea",
        "primary-container": "#007f4e",
        "on-tertiary-fixed": "#141b2b",
        "surface-container-high": "#e2e8f8",
        secondary: "#55615d",
        "surface-container-low": "#f0f3ff",
        "outline-variant": "#bdcabf",
        "on-secondary": "#ffffff",
        "surface-bright": "#f9f9ff",
        "surface-container": "#e7eefe",
        outline: "#6e7a70",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "sidebar-width": "260px",
        gutter: "16px",
        base: "4px",
        "container-padding": "24px",
        "card-gap": "20px",
      },
      fontFamily: {
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
